name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: sudo apt install cmake
    - name: Submodules
      run: git submodule init && git submodule update --init --recursive
    - name: configure
      run: cmake .
    - name: make
      run: make
    - name: tests
      run: make test
    - name: Docker
      run: docker build -t dog .
